// BLUE BUTTONS
export const BUTTON_BLUE_SOLID = "BUTTON_BLUE_SOLID";
export const BUTTON_LIGHT_BLUE_SOLID = "BUTTON_LIGHT_BLUE_SOLID";
export const BUTTON_BLUE_OUTLINED = "BUTTON_BLUE_OUTLINED";

// TRANSPARENT BUTTONS
export const BUTTON_TRANSPARENT = "BUTTON_TRANSPARENT";
